apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx
  namespace: external-services
spec:
  interval: 5m
  url: https://github.com/MGTheTrain/gitops-poc.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: internal-apps
spec:
  interval: 10m
  targetNamespace: internal-apps
  sourceRef:
    kind: GitRepository
    name: nginx
  path: "./gitops/kustomize/nginx/overlays/dev"
  prune: true
  timeout: 1m