apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample-service
  namespace: external-services # refers to the namespace where the Kustomization resources itself are created
spec:
  interval: 5m
  url: https://github.com/MGTheTrain/gitops-poc.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-service
  namespace: internal-apps
spec:
  interval: 10m
  targetNamespace: internal-apps
  sourceRef:
    kind: GitRepository
    name: sample-service
  path: "./gitops/kustomize/sample-service/overlays/prd"
  prune: true
  timeout: 1m