apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-service-app
  namespace: external-services # refers to the namespace where the ArgoCD resources itself are created
spec:
  project: default
  source:
    repoURL: https://github.com/MGTheTrain/gitops-poc.git
    path: ./gitops/helm/sample-service/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true